### ISSUE TITLE
Soundpacks on curseforge?

### ISSUE THREAD

**Issue by facetorched** [makamys/MAtmos-2020-Zen#2]
It would be dope if soundpacks like this were on curseforge under the resourcepack section since it would make it easier to distribute it.

**Comment by makamys** [comment]
This is a valid idea, but my upload speed is terrible and it would be extra work :sweat_smile:. What do you mean by easier to distribute though, is there anything wrong with GitHub?

**Comment by facetorched** [comment]
Modpacks. Curse modpacks are kind of the new standard.

If it's just the amount of work, would the license prevent me from uploading it myself? I would rather not take credit for something that isn't mine but if you support it i will go ahead.

**Comment by makamys** [comment]
Ooh, right, that makes sense.
The pack's under MIT, so you can redistribute it all you want as long as you keep the LICENSE file intact (which fulfills the purpose of attribution).

**Comment by makamys** [comment]
On second though, I'll do this myself. Having to depend on someone else to do this would complicate the management of things too much.

**Comment by facetorched** [comment]
Awesome. Hope it's not too much work 🙂

**Comment by makamys** [comment]
It would only be work when setting it up the first time, assuming curse has a usable API. We'll see.

**Comment by makamys** [comment]
They're up!
